### ISSUE TITLE
Feedback request [AWS-34 AWS Cloudwatch.]

### ISSUE THREAD

**Issue by Rithmatist** [Rithmatist/cloud-6-repo-Rithmatist#1]
# Feedback Request [AWS-34 AWS Cloudwatch.]
Permalink naar bestand: [[LINK](https://github.com/Rithmatist/cloud-6-repo-Rithmatist/blob/main/05_Cloud_2/AWS-34%20AWS%20Cloudwatch.md)]

Template voor reviewers:
```
## Samenvatting
- Beschrijft de samenvatting het onderwerp volledig genoeg?
- Is de samenvatting in eigen woorden geschreven?
- Mist er cruciale informatie in de samenvatting?
- Is de beschrijving duidelijk genoeg?

## Key Terms
- Missen er sleutelwoorden?
- Zijn de sleutelwoorden goed uitgelegd?

## Bronnen
- Zijn bronnen vernoemd?
- Zijn de genoemde bronnen juist?

## Opdracht
(Waar van toepassing)
- Is het resultaat correct?
- Zijn de ervaren problemen en oplossingen goed beschreven?
```
Deel de link van de issue met je groepsgenoten.

**Comment by rupaliBC** [comment]
## Samenvatting
- Good explaination and very clear summary of the subject!

## Key Terms
- No Key terms defined.

## Bronnen
- Reference links are mentioned.

## Opdracht
This assignment has step by step explaination of the cloudwatch lab . It also includes enough images to support the lab.

**Comment by Rithmatist** [comment]
@rupaliBC Bedankt voor je feedback! 👍
